site_name: TerriaJS
theme:
  name: material
  logo: terria.png
docs_dir: doc
site_dir: ../wwwroot/doc/guide
markdown_extensions:
  - markdown.extensions.admonition
strict: false
extra_javascript:
  - js/rewrite-links.js
nav:
  - Home: README.md
  - Getting Started: getting-started.md
  - Customizing:
      - Overview: customizing/README.md
      - Client-side Config: customizing/client-side-config.md
      - Initialization Files: customizing/initialization-files.md
      - Server-side Config: customizing/server-side-config.md
      - Cloning and Building: customizing/cloning-and-building.md
      - Skinning: customizing/skinning.md
      - Translation guide: customizing/translation-guide.md
      - Search Providers: customizing/search-providers.md
  - Connecting to Data:
      - Overview: connecting-to-data/README.md
      - Cross-Origin Resource Sharing: connecting-to-data/cross-origin-resource-sharing.md
      - Catalog Groups: connecting-to-data/catalog-groups.md
      - Catalog Items: connecting-to-data/catalog-items.md
      - Customizing Data Appearance:
          - Overview: connecting-to-data/customizing-data-appearance/overview.md
          - Imagery Data: connecting-to-data/customizing-data-appearance/imagery-data.md
          - Tabular Data: connecting-to-data/customizing-data-appearance/tabular-data.md
          - Feature Information Template: connecting-to-data/customizing-data-appearance/feature-info-template.md
      - Catalog Functions: connecting-to-data/catalog-functions.md
      - Catalog References: connecting-to-data/catalog-references.md
      - Catalog Type Details:
  - Deploying:
      - Overview: deploying/README.md
      - Deploying TerriaMap: deploying/deploying-terriamap.md
      - Deploying with Kubernetes: deploying/deploying-with-kubernetes.md
      - Setting Up a Region Mapping Server: deploying/setting-up-a-region-mapping-server.md
      - Setting Up Geoserver: deploying/setting-up-geoserver.md
      - Using as a CKAN Previewer: deploying/using-as-a-ckan-previewer.md
      - Controlling with URL Parameters: deploying/controlling-with-url-parameters.md
      - Controlling in an &lt;iframe&gt; or Popup: deploying/controlling-in-an-iframe-or-popup.md
  - Contributing:
      - Overview: contributing/README.md
      - Development Environment: contributing/development-environment.md
      - Architecture: contributing/architecture.md
      - Using a Custom Version of Cesium: contributing/using-a-custom-version-of-cesium.md
      - Setting up Saucelabs: contributing/setting-up-saucelabs.md
      - Problems and Solutions: contributing/problems-and-solutions.md
      - New model layer documentation: contributing/model-layer.md
      - Traits in depth: contributing/traits-in-depth.md
      - Strata Examples: contributing/strata-examples.md
      - Init sources: contributing/init-sources.md
      - Frontend style guide: contributing/frontend-style-guide.md
      - Version 8 migration guide: contributing/migration-guide.md
      - Development translation guide: contributing/translation-guide-dev.md
  - Acknowledgements:
      - Attributions: acknowledgements/attributions.md
