terriamap:
    serverConfig:
        port: 3001
        allowProxyFor: [
            "nicta.com.au",
            "gov.au",
            "csiro.au",
            "arcgis.com",
            "argo.jcommops.org",
            "www.abc.net.au",
            "geoserver.aurin.org.au",
            "mapsengine.google.com",
            "s3-ap-southeast-2.amazonaws.com",
            "adelaidecitycouncil.com",
            "www.dptiapps.com.au",
            "geoserver-123.aodn.org.au",
            "geoserver.imos.org.au",
            "nci.org.au",
            "static.nationalmap.nicta.com.au",
            "githubusercontent.com",
            "gov",
            "gov.uk",
            "gov.nz",
            "sample.aero3dpro.com.au"
        ]
        initPaths:
        - "/etc/config/client"
        newShareUrlPrefix: "s"
        shareUrlPrefixes:
            s:
                service: "s3"
                region: "ap-southeast-2"
                bucket: "terriajs-ci-sharing"
                accessKeyId: "secret"
                secretAccessKey: "secret"
        feedback:
            userAgent: TerriaBot (TerriaJS Feedback)
            issuesUrl: https://api.github.com/repos/TerriaJS/demo-feedback/issues
            accessToken: secret
    clientConfig:
        initializationUrls:
        - helm
        - terria
        parameters:
            bingMapsKey: "AiKyh8RfSWfiQyzh1iaiL2EBSwKK0EoB1dFpvApJZs3KibbXtxclGaj5540y70Si"
            cesiumIonAccessToken: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxZDY5MDE1YS0yNGFlLTQ1MzctYWNkNy0wNDQ1YWNiNTM5MDIiLCJpZCI6Mjk5Miwic2NvcGVzIjpbImFzciIsImdjIl0sImlhdCI6MTUzODAzMzgyNn0.a2uTotdiHUo8FiHsO4MVNZ1KT5pOF0rb7CFdwbRAsOo"
            googleAnalyticsKey:
            disclaimer:
                text: "Disclaimer: This map must not be used for navigation or precise spatial analysis"
                url: "https://terria.io"
            developerAttribution:
                text: "Terria"
                link: "https://terria.io"
            appName: "TerriaJS Continuous Integration"
            brandBarElements: ["", "<a target=\"_blank\" href=\"http://terria.io\"><img src=\"images/terria_logo.png\" height=\"52\" title=\"Version: {{version}}\" /></a>", ""]
            supportEmail: "info@terria.io"
            mobileDefaultViewerMode: "2d"
            experimentalFeatures: true
            feedbackUrl: "feedback"
    resources:
        requests:
            cpu: 10m
            memory: 10Mi
